[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

monitor_speed = 115200

lib_deps =
    arduino-libraries/Ethernet

build_flags =
    -D REAR_CMD_UDP_PORT=12000
    -D W5500_CS_PIN=PA4
